version: '3.8'

services:
  next-app:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db

  db:
      image: mongo:latest
      restart: unless-stopped
      volumes:
        - mongodb-data:/data/db
      environment:
        MONGO_INITDB_DATABASE: payload

volumes:
  mongodb-data:
